version: '2.4'
services:
  nginx:
    build:
      context: ./docker/nginx/
      args:
        - TZ=${TZ}

  php:
    build:
      context: ./docker/php/
      args:
        - TZ=${TZ}
    tty: true

  postgres:
    build:
      context: ./docker/postgres
      args:
        - TZ=${TZ}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 10
