INSERT INTO articles (author_id, title, text, created_at)
VALUES (1, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mollis vulputate metus ut venenatis. Nunc at libero dui. Vivamus luctus aliquet porttitor. Ut non condimentum elit. Suspendisse pharetra lectus vitae urna facilisis commodo. Nunc orci neque, faucibus eu eros convallis, mattis interdum dolor. Praesent consectetur eget nibh ut sagittis. Pellentesque pharetra nisl vitae congue euismod. Morbi tempus et purus quis accumsan. Sed id imperdiet augue. Vivamus euismod lectus ut dignissim porttitor. Integer varius elit vitae hendrerit feugiat.

Nam iaculis est ex, in cursus eros aliquet a. Vestibulum faucibus nisi lobortis tortor eleifend, id fermentum leo sodales. Praesent suscipit purus quis sodales egestas. Integer sed lectus in magna blandit consequat. Morbi sagittis leo sed ex maximus, ut iaculis ipsum tincidunt. Proin leo felis, pulvinar eu nisi vitae, pretium cursus eros. Aliquam maximus nisi ac nisi hendrerit pharetra. Vestibulum et lectus et metus feugiat facilisis ut eget ex. Proin commodo, enim nec vulputate vulputate, sapien mi interdum leo, varius tempus sapien turpis at odio. Maecenas et varius arcu. Aenean rutrum tellus vel velit faucibus mattis. Aenean eget dui sit amet ligula luctus lacinia a at eros. Nunc mattis condimentum massa ac tristique.

Nullam in malesuada lorem, eu malesuada felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam ut facilisis est. Mauris vel dignissim ipsum, in gravida augue. Nam sagittis felis a tempus tempor. Donec aliquam consectetur gravida. Maecenas tincidunt erat sed nisl sodales efficitur. Donec varius mollis velit, vel gravida nulla ultricies sit amet. Nulla facilisi. Cras feugiat, lorem id mollis pharetra, nibh leo sodales orci, non convallis velit turpis vitae nunc. Aliquam erat volutpat. Suspendisse suscipit sem sed lorem accumsan, at fermentum sem facilisis viverra fusce.',
        '2022-07-23T15:23:00+03:00'),
       (2, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mollis vulputate metus ut venenatis. Nunc at libero dui. Vivamus luctus aliquet porttitor. Ut non condimentum elit. Suspendisse pharetra lectus vitae urna facilisis commodo. Nunc orci neque, faucibus eu eros convallis, mattis interdum dolor. Praesent consectetur eget nibh ut sagittis. Pellentesque pharetra nisl vitae congue euismod. Morbi tempus et purus quis accumsan. Sed id imperdiet augue. Vivamus euismod lectus ut dignissim porttitor. Integer varius elit vitae hendrerit feugiat.

Nam iaculis est ex, in cursus eros aliquet a. Vestibulum faucibus nisi lobortis tortor eleifend, id fermentum leo sodales. Praesent suscipit purus quis sodales egestas. Integer sed lectus in magna blandit consequat. Morbi sagittis leo sed ex maximus, ut iaculis ipsum tincidunt. Proin leo felis, pulvinar eu nisi vitae, pretium cursus eros. Aliquam maximus nisi ac nisi hendrerit pharetra. Vestibulum et lectus et metus feugiat facilisis ut eget ex. Proin commodo, enim nec vulputate vulputate, sapien mi interdum leo, varius tempus sapien turpis at odio. Maecenas et varius arcu. Aenean rutrum tellus vel velit faucibus mattis. Aenean eget dui sit amet ligula luctus lacinia a at eros. Nunc mattis condimentum massa ac tristique.

Nullam in malesuada lorem, eu malesuada felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam ut facilisis est. Mauris vel dignissim ipsum, in gravida augue. Nam sagittis felis a tempus tempor. Donec aliquam consectetur gravida. Maecenas tincidunt erat sed nisl sodales efficitur. Donec varius mollis velit, vel gravida nulla ultricies sit amet. Nulla facilisi. Cras feugiat, lorem id mollis pharetra, nibh leo sodales orci, non convallis velit turpis vitae nunc. Aliquam erat volutpat. Suspendisse suscipit sem sed lorem accumsan, at fermentum sem facilisis viverra fusce.',
        '2022-07-23T15:24:00+03:00'),
       (1, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mollis vulputate metus ut venenatis. Nunc at libero dui. Vivamus luctus aliquet porttitor. Ut non condimentum elit. Suspendisse pharetra lectus vitae urna facilisis commodo. Nunc orci neque, faucibus eu eros convallis, mattis interdum dolor. Praesent consectetur eget nibh ut sagittis. Pellentesque pharetra nisl vitae congue euismod. Morbi tempus et purus quis accumsan. Sed id imperdiet augue. Vivamus euismod lectus ut dignissim porttitor. Integer varius elit vitae hendrerit feugiat.

Nam iaculis est ex, in cursus eros aliquet a. Vestibulum faucibus nisi lobortis tortor eleifend, id fermentum leo sodales. Praesent suscipit purus quis sodales egestas. Integer sed lectus in magna blandit consequat. Morbi sagittis leo sed ex maximus, ut iaculis ipsum tincidunt. Proin leo felis, pulvinar eu nisi vitae, pretium cursus eros. Aliquam maximus nisi ac nisi hendrerit pharetra. Vestibulum et lectus et metus feugiat facilisis ut eget ex. Proin commodo, enim nec vulputate vulputate, sapien mi interdum leo, varius tempus sapien turpis at odio. Maecenas et varius arcu. Aenean rutrum tellus vel velit faucibus mattis. Aenean eget dui sit amet ligula luctus lacinia a at eros. Nunc mattis condimentum massa ac tristique.

Nullam in malesuada lorem, eu malesuada felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam ut facilisis est. Mauris vel dignissim ipsum, in gravida augue. Nam sagittis felis a tempus tempor. Donec aliquam consectetur gravida. Maecenas tincidunt erat sed nisl sodales efficitur. Donec varius mollis velit, vel gravida nulla ultricies sit amet. Nulla facilisi. Cras feugiat, lorem id mollis pharetra, nibh leo sodales orci, non convallis velit turpis vitae nunc. Aliquam erat volutpat. Suspendisse suscipit sem sed lorem accumsan, at fermentum sem facilisis viverra fusce.',
        '2022-07-23T15:25:00+03:00'),
       (3, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse mollis vulputate metus ut venenatis. Nunc at libero dui. Vivamus luctus aliquet porttitor. Ut non condimentum elit. Suspendisse pharetra lectus vitae urna facilisis commodo. Nunc orci neque, faucibus eu eros convallis, mattis interdum dolor. Praesent consectetur eget nibh ut sagittis. Pellentesque pharetra nisl vitae congue euismod. Morbi tempus et purus quis accumsan. Sed id imperdiet augue. Vivamus euismod lectus ut dignissim porttitor. Integer varius elit vitae hendrerit feugiat.

Nam iaculis est ex, in cursus eros aliquet a. Vestibulum faucibus nisi lobortis tortor eleifend, id fermentum leo sodales. Praesent suscipit purus quis sodales egestas. Integer sed lectus in magna blandit consequat. Morbi sagittis leo sed ex maximus, ut iaculis ipsum tincidunt. Proin leo felis, pulvinar eu nisi vitae, pretium cursus eros. Aliquam maximus nisi ac nisi hendrerit pharetra. Vestibulum et lectus et metus feugiat facilisis ut eget ex. Proin commodo, enim nec vulputate vulputate, sapien mi interdum leo, varius tempus sapien turpis at odio. Maecenas et varius arcu. Aenean rutrum tellus vel velit faucibus mattis. Aenean eget dui sit amet ligula luctus lacinia a at eros. Nunc mattis condimentum massa ac tristique.

Nullam in malesuada lorem, eu malesuada felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam ut facilisis est. Mauris vel dignissim ipsum, in gravida augue. Nam sagittis felis a tempus tempor. Donec aliquam consectetur gravida. Maecenas tincidunt erat sed nisl sodales efficitur. Donec varius mollis velit, vel gravida nulla ultricies sit amet. Nulla facilisi. Cras feugiat, lorem id mollis pharetra, nibh leo sodales orci, non convallis velit turpis vitae nunc. Aliquam erat volutpat. Suspendisse suscipit sem sed lorem accumsan, at fermentum sem facilisis viverra fusce.',
        '2022-07-23T15:25:00+03:00');

INSERT INTO comments(author_id, article_id, name, url, email, created_at, text)
VALUES (1, 3, 'test name', null, null, '2022-07-23T16:20:00+03:00', 'lorem ipsum bla bla comment1'),
       (2, 3, 'test name2', 'https://example.com', 'email@example.com', '2022-07-23T16:21:00+03:00', 'lorem ipsum bla bla comment2'),
       (1, 3, 'test name3', 'https://example.com', null, '2022-07-23T16:22:00+03:00', 'lorem ipsum bla bla comment3'),
       (2, 3, 'test name4', null, 'email@example.com', '2022-07-23T16:23:00+03:00', 'lorem ipsum bla bla comment4');